/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

public class HelperFunctions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected HelperFunctions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HelperFunctions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() /* no exception */ {
    if(swigCPtr != 0 && swigCMemOwn) {
	swigCMemOwn = false;
	throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
 }

  public static boolean testXmlData() throws XmlException {
    return dbxml_javaJNI.HelperFunctions_testXmlData();
  }

  public static boolean testConfigDefault(XmlContainerConfig javaDefault) throws XmlException {
    return dbxml_javaJNI.HelperFunctions_testConfigDefault( javaDefault.pack(), javaDefault.getCompression() );
  }

  public static boolean testConfigBitOperator(XmlManager mgr) throws XmlException {
    return dbxml_javaJNI.HelperFunctions_testConfigBitOperator(XmlManager.getCPtr(mgr), mgr);
  }

  public static boolean testNullTxn(XmlManager mgr) throws XmlException {
    return dbxml_javaJNI.HelperFunctions_testNullTxn(XmlManager.getCPtr(mgr), mgr);
  }

  public static int getType(String URI, String name, String value) throws XmlException {
    return dbxml_javaJNI.HelperFunctions_getType(URI, name, value);
  }

  protected static String getTypeURI(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_getTypeURI(data, XmlResults.getCPtr(result), result);
  }

  protected static String getTypeName(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_getTypeName(data, XmlResults.getCPtr(result), result);
  }

  protected static String asString(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_asString(data, XmlResults.getCPtr(result), result);
  }

  protected static XmlDocument asDocument(byte[] data, XmlResults result) { return dbxml_javaJNI.HelperFunctions_asDocument(data, XmlResults.getCPtr(result), result); }

  protected static XmlEventReader asEventReader(byte[] data, XmlResults result) {
    return new XmlEventReader(dbxml_javaJNI.HelperFunctions_asEventReader(data, XmlResults.getCPtr(result), result), false);
  }

  protected static String getNodeHandle(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_getNodeHandle(data, XmlResults.getCPtr(result), result);
  }

  protected static String getNodeName(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_getNodeName(data, XmlResults.getCPtr(result), result);
  }

  protected static String getNodeValue(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_getNodeValue(data, XmlResults.getCPtr(result), result);
  }

  protected static String getNamespaceURI(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_getNamespaceURI(data, XmlResults.getCPtr(result), result);
  }

  protected static String getPrefix(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_getPrefix(data, XmlResults.getCPtr(result), result);
  }

  protected static String getLocalName(byte[] data, XmlResults result) {
    return dbxml_javaJNI.HelperFunctions_getLocalName(data, XmlResults.getCPtr(result), result);
  }

  protected static XmlValue getParentNode(byte[] data, XmlResults result) { return dbxml_javaJNI.HelperFunctions_getParentNode(data, XmlResults.getCPtr(result), result); }

  protected static XmlValue getFirstChild(byte[] data, XmlResults result) { return dbxml_javaJNI.HelperFunctions_getFirstChild(data, XmlResults.getCPtr(result), result); }

  protected static XmlValue getLastChild(byte[] data, XmlResults result) { return dbxml_javaJNI.HelperFunctions_getLastChild(data, XmlResults.getCPtr(result), result); }

  protected static XmlValue getPreviousSibling(byte[] data, XmlResults result) { return dbxml_javaJNI.HelperFunctions_getPreviousSibling(data, XmlResults.getCPtr(result), result); }

  protected static XmlValue getNextSibling(byte[] data, XmlResults result) { return dbxml_javaJNI.HelperFunctions_getNextSibling(data, XmlResults.getCPtr(result), result); }

  protected static XmlResults getAttributes(byte[] data, XmlResults result) {
    long cPtr = dbxml_javaJNI.HelperFunctions_getAttributes(data, XmlResults.getCPtr(result), result);
    return (cPtr == 0) ? null : new XmlResults(cPtr, true);
  }

  protected static XmlValue getOwnerElement(byte[] data, XmlResults result) { return dbxml_javaJNI.HelperFunctions_getOwnerElement(data, XmlResults.getCPtr(result), result); }

  public static XmlValue createDocumentValue(XmlDocument doc) throws XmlException { return dbxml_javaJNI.HelperFunctions_createDocumentValue(doc); }

  public static XmlResults createResults(XmlTransaction txn, XmlManager mgr) throws XmlException {
    return new XmlResults(dbxml_javaJNI.HelperFunctions_createResults(XmlTransaction.getCPtr(txn), txn, XmlManager.getCPtr(mgr), mgr), true);
  }

  protected static String getAtomicTypeName(int type, String v) {
    return dbxml_javaJNI.HelperFunctions_getAtomicTypeName(type, v);
  }

  protected static String getAtomicTypeURI(int type, String v) {
    return dbxml_javaJNI.HelperFunctions_getAtomicTypeURI(type, v);
  }

  protected static void validateString(int type, String v) {
    dbxml_javaJNI.HelperFunctions_validateString(type, v);
  }

  protected static XmlInputStream getContentAsXmlInputStream(XmlDocument doc) {
    long cPtr = dbxml_javaJNI.HelperFunctions_getContentAsXmlInputStream(doc);
    return (cPtr == 0) ? null : new XmlInputStream(cPtr, true);
  }

  protected static XmlEventReader getContentAsEventReader(XmlDocument doc) {
    return new XmlEventReader(dbxml_javaJNI.HelperFunctions_getContentAsEventReader(doc), true);
  }

  protected static void getContentAsEventWriter(XmlDocument doc, XmlEventWriter writer) throws XmlException {
    dbxml_javaJNI.HelperFunctions_getContentAsEventWriter(doc, XmlEventWriter.getCPtr(writer), writer);
  }

  protected static String getContentAsString(XmlDocument doc) {
    return dbxml_javaJNI.HelperFunctions_getContentAsString(doc);
  }

  public static XmlValue getMetaData(String uri, String name, XmlDocument doc) throws XmlException { return dbxml_javaJNI.HelperFunctions_getMetaData(uri, name, doc); }

  public static String verifyDefaultCollection(XmlManager mgr, String defaultCollection, String baseURI) throws XmlException {
    return dbxml_javaJNI.HelperFunctions_verifyDefaultCollection(XmlManager.getCPtr(mgr), mgr, defaultCollection, baseURI);
  }

  public static void verifyBaseURI(XmlManager mgr, String baseURI) throws XmlException {
    dbxml_javaJNI.HelperFunctions_verifyBaseURI(XmlManager.getCPtr(mgr), mgr, baseURI);
  }

}
