/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

public class XmlArguments {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlArguments(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlArguments obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() /* no exception */ {
    if(swigCPtr != 0 && swigCMemOwn) {
	swigCMemOwn = false;
	dbxml_javaJNI.delete_XmlArguments(swigCPtr);
    }
    swigCPtr = 0;
 }

  public XmlResults getArgument(int index) throws XmlException {
    return new XmlResults(dbxml_javaJNI.XmlArguments_getArgument(swigCPtr, this, index), true);
  }

  public long getNumberOfArgs() throws XmlException {
    return dbxml_javaJNI.XmlArguments_getNumberOfArgs(swigCPtr, this);
  }

}
