/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

public class XmlCompression {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlCompression(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlCompression obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() /* no exception */ {
    if(swigCPtr != 0 && swigCMemOwn) {
	swigCMemOwn = false;
	dbxml_javaJNI.delete_XmlCompression(swigCPtr);
    }
    swigCPtr = 0;
 }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() throws XmlException {
    swigCMemOwn = false;
    dbxml_javaJNI.XmlCompression_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() throws XmlException {
    swigCMemOwn = true;
    dbxml_javaJNI.XmlCompression_change_ownership(this, swigCPtr, true);
  }

  protected XmlCompression() {
    this(dbxml_javaJNI.new_XmlCompression(), true);
    dbxml_javaJNI.XmlCompression_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean compress(XmlTransaction txn, XmlData source, XmlData dest) throws XmlException {
    return dbxml_javaJNI.XmlCompression_compress(swigCPtr, this, XmlTransaction.getCPtr(txn), txn, XmlData.getCPtr(source), source, XmlData.getCPtr(dest), dest);
  }

  public boolean decompress(XmlTransaction txn, XmlData source, XmlData dest) throws XmlException {
    return dbxml_javaJNI.XmlCompression_decompress(swigCPtr, this, XmlTransaction.getCPtr(txn), txn, XmlData.getCPtr(source), source, XmlData.getCPtr(dest), dest);
  }

}
