/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

public class XmlEventWriter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlEventWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlEventWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
	swigCMemOwn = false;
	dbxml_javaJNI.delete_XmlEventWriter(swigCPtr);
    }
    swigCPtr = 0;
}

    public void close()
	/* wrapper for close that protects from double-close */
	throws XmlException {
	if (swigCPtr != 0) {
	    try {
	        closeInternal();
	    } catch(XmlException e) {
	        swigCPtr = 0;
	        throw e;
	    }
	    swigCPtr = 0;
	}
    }
    protected void release()
    {
	swigCMemOwn = false;
	swigCPtr = 0;
    }
    
  public void closeInternal() throws XmlException {
    dbxml_javaJNI.XmlEventWriter_closeInternal(swigCPtr, this);
  }

  public void writeAttribute(String localName, String prefix, String uri, String value, boolean isSpecified) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeAttribute(swigCPtr, this, localName, prefix, uri, value, isSpecified);
  }

  public void writeText(int type, String text, int length) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeText__SWIG_0(swigCPtr, this, type, text, length);
  }

  public void writeDTD(String dtd, int length) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeDTD__SWIG_0(swigCPtr, this, dtd, length);
  }

  public void writeText(int type, String text) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeText__SWIG_1(swigCPtr, this, type, text);
  }

  public void writeDTD(String dtd) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeDTD__SWIG_1(swigCPtr, this, dtd);
  }

  public void writeProcessingInstruction(String target, String data) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeProcessingInstruction(swigCPtr, this, target, data);
  }

  public void writeStartElement(String localName, String prefix, String uri, int numAttributes, boolean isEmpty) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeStartElement(swigCPtr, this, localName, prefix, uri, numAttributes, isEmpty);
  }

  public void writeEndElement(String localName, String prefix, String uri) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeEndElement(swigCPtr, this, localName, prefix, uri);
  }

  public void writeStartDocument(String version, String encoding, String standalone) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeStartDocument(swigCPtr, this, version, encoding, standalone);
  }

  public void writeEndDocument() throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeEndDocument(swigCPtr, this);
  }

  public void writeStartEntity(String name, boolean expandedInfoFollows) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeStartEntity(swigCPtr, this, name, expandedInfoFollows);
  }

  public void writeEndEntity(String name) throws XmlException {
    dbxml_javaJNI.XmlEventWriter_writeEndEntity(swigCPtr, this, name);
  }

}
