/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

public class XmlExternalFunctionBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlExternalFunctionBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlExternalFunctionBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() /* no exception */ {
    if(swigCPtr != 0 && swigCMemOwn) {
	swigCMemOwn = false;
	dbxml_javaJNI.delete_XmlExternalFunctionBase(swigCPtr);
    }
    swigCPtr = 0;
 }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() throws XmlException {
    swigCMemOwn = false;
    dbxml_javaJNI.XmlExternalFunctionBase_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() throws XmlException {
    swigCMemOwn = true;
    dbxml_javaJNI.XmlExternalFunctionBase_change_ownership(this, swigCPtr, true);
  }

  protected XmlExternalFunctionBase() {
    this(dbxml_javaJNI.new_XmlExternalFunctionBase(), true);
    dbxml_javaJNI.XmlExternalFunctionBase_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public XmlResults execute(XmlTransaction txn, XmlManager mgr, XmlArguments args) throws XmlException {
    return new XmlResults(dbxml_javaJNI.XmlExternalFunctionBase_execute(swigCPtr, this, XmlTransaction.getCPtr(txn), txn, XmlManager.getCPtr(mgr), mgr, XmlArguments.getCPtr(args), args), true);
  }

  public void close() throws XmlException {
    dbxml_javaJNI.XmlExternalFunctionBase_close(swigCPtr, this);
  }

}
