/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

public class XmlEventReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlEventReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlEventReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
	swigCMemOwn = false;
	dbxml_javaJNI.delete_XmlEventReader(swigCPtr);
    }
    swigCPtr = 0;
}

    public void close()
	/* wrapper for close that protects from double-close */
	throws XmlException {
	if (swigCPtr != 0) {
	    closeInternal();
	    swigCPtr = 0;
	}
    }
    protected void release()
    {
	swigCMemOwn = false;
	swigCPtr = 0;
    }
    
  public void closeInternal() throws XmlException {
    dbxml_javaJNI.XmlEventReader_closeInternal(swigCPtr, this);
  }

  public void setReportEntityInfo(boolean value) throws XmlException {
    dbxml_javaJNI.XmlEventReader_setReportEntityInfo(swigCPtr, this, value);
  }

  public boolean getReportEntityInfo() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getReportEntityInfo(swigCPtr, this);
  }

  public void setExpandEntities(boolean value) throws XmlException {
    dbxml_javaJNI.XmlEventReader_setExpandEntities(swigCPtr, this, value);
  }

  public boolean getExpandEntities() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getExpandEntities(swigCPtr, this);
  }

  public int next() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_next(swigCPtr, this);
  }

  public int nextTag() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_nextTag(swigCPtr, this);
  }

  public boolean hasNext() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_hasNext(swigCPtr, this);
  }

  public int getEventType() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getEventType(swigCPtr, this);
  }

  public String getNamespaceURI() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getNamespaceURI(swigCPtr, this);
 }

  public String getLocalName() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getLocalName(swigCPtr, this);
 }

  public String getPrefix() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getPrefix(swigCPtr, this);
 }

  public String getValue() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getValue(swigCPtr, this);
 }

  public int getAttributeCount() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getAttributeCount(swigCPtr, this);
  }

  public boolean isAttributeSpecified(int index) throws XmlException {
    return dbxml_javaJNI.XmlEventReader_isAttributeSpecified(swigCPtr, this, index);
  }

  public String getAttributeLocalName(int index) throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getAttributeLocalName(swigCPtr, this, index);
 }

  public String getAttributeNamespaceURI(int index) throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getAttributeNamespaceURI(swigCPtr, this, index);
 }

  public String getAttributePrefix(int index) throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getAttributePrefix(swigCPtr, this, index);
 }

  public String getAttributeValue(int index) throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getAttributeValue(swigCPtr, this, index);
 }

  public String getEncoding() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getEncoding(swigCPtr, this);
 }

  public String getVersion() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getVersion(swigCPtr, this);
 }

  public String getSystemId() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_getSystemId(swigCPtr, this);
 }

  public boolean isStandalone() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_isStandalone(swigCPtr, this);
  }

  public boolean standaloneSet() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_standaloneSet(swigCPtr, this);
  }

  public boolean encodingSet() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_encodingSet(swigCPtr, this);
  }

  public boolean hasEntityEscapeInfo() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_hasEntityEscapeInfo(swigCPtr, this);
  }

  public boolean needsEntityEscape(int index) throws XmlException {
    return dbxml_javaJNI.XmlEventReader_needsEntityEscape__SWIG_0(swigCPtr, this, index);
  }

  public boolean needsEntityEscape() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_needsEntityEscape__SWIG_1(swigCPtr, this);
  }

  public boolean hasEmptyElementInfo() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_hasEmptyElementInfo(swigCPtr, this);
  }

  public boolean isEmptyElement() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_isEmptyElement(swigCPtr, this);
  }

  public boolean isWhiteSpace() throws XmlException {
    return dbxml_javaJNI.XmlEventReader_isWhiteSpace(swigCPtr, this);
  }

  public final static int StartElement = 0;
  public final static int EndElement = StartElement + 1;
  public final static int Characters = EndElement + 1;
  public final static int CDATA = Characters + 1;
  public final static int Comment = CDATA + 1;
  public final static int Whitespace = Comment + 1;
  public final static int StartDocument = Whitespace + 1;
  public final static int EndDocument = StartDocument + 1;
  public final static int StartEntityReference = EndDocument + 1;
  public final static int EndEntityReference = StartEntityReference + 1;
  public final static int ProcessingInstruction = EndEntityReference + 1;
  public final static int DTD = ProcessingInstruction + 1;

}
