/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

public class XmlStackFrame {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlStackFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlStackFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() /* no exception */ {
    if(swigCPtr != 0 && swigCMemOwn) {
	swigCMemOwn = false;
	throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
 }

  public String getQueryFile() throws XmlException {
    return dbxml_javaJNI.XmlStackFrame_getQueryFile(swigCPtr, this);
  }

  public int getQueryLine() throws XmlException {
    return dbxml_javaJNI.XmlStackFrame_getQueryLine(swigCPtr, this);
  }

  public int getQueryColumn() throws XmlException {
    return dbxml_javaJNI.XmlStackFrame_getQueryColumn(swigCPtr, this);
  }

  public XmlResults query(String queryString) throws XmlException {
    return new XmlResults(dbxml_javaJNI.XmlStackFrame_query(swigCPtr, this, queryString), true);
  }

  public String getQueryPlan() throws XmlException {
    return dbxml_javaJNI.XmlStackFrame_getQueryPlan(swigCPtr, this);
  }

  public XmlStackFrame getPreviousStackFrame() throws XmlException {
    long cPtr = dbxml_javaJNI.XmlStackFrame_getPreviousStackFrame(swigCPtr, this);
    return (cPtr == 0) ? null : new XmlStackFrame(cPtr, false);
  }

}
